### ISSUE TITLE
Allow to use alarm bytes of DS18B20 for temporary persistent storage

### ISSUE THREAD

**Issue by HTRamsey** [MaJerle/onewire_uart#12]
Sometimes I will store my own config values on these, and having a built in API to read/write upper & lower bytes separately could be useful for other people as well.

**Comment by MaJerle** [comment]
You would like to read the DS18X20 config bytes and store them somewhere in your flash?

Can't you do this by using lwow core functions to reset/match/read ?

**Comment by HTRamsey** [comment]
Yeah I was just thinking something like a convenience getter function lwow_ds18x20_get_alarm_temp would be useful have available in the API. And also a getter for conversion time based on resolution. Just some ideas.

**Comment by MaJerle** [comment]
I'm not able to test, but you can try, if it works: https://github.com/MaJerle/lwow/tree/develop-get-alarm

**Comment by HTRamsey** [comment]
I guess you don't need to read the conf byte but looks good otherwise

**Comment by MaJerle** [comment]
You tried or just looked at code? :)

**Comment by HTRamsey** [comment]
works fine, tested with ds18b20 on stm32

**Comment by MaJerle** [comment]
FYI, I have added also an option to call *match or skip* depending on the parameter rom_id.
+ you have been added as an author in the file.
